// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCKnNutN-9l10UtlZQV7ow7cws9c8ezII',
    appId: '1:650617212741:web:126e0e177db024b3f5382c',
    messagingSenderId: '650617212741',
    projectId: 'travellookup-3fda3',
    authDomain: 'travellookup-3fda3.firebaseapp.com',
    storageBucket: 'travellookup-3fda3.firebasestorage.app',
    measurementId: 'G-HG1F4C5KRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7G1CBGYQ8om2HjjnmP-u1RKQfw0pFn80',
    appId: '1:650617212741:android:50c9495d58789011f5382c',
    messagingSenderId: '650617212741',
    projectId: 'travellookup-3fda3',
    storageBucket: 'travellookup-3fda3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRLlxfgsz0VCQEVDclP0moUgSF1D5T8fE',
    appId: '1:650617212741:ios:1644ee49c2190c62f5382c',
    messagingSenderId: '650617212741',
    projectId: 'travellookup-3fda3',
    storageBucket: 'travellookup-3fda3.firebasestorage.app',
    iosClientId: '650617212741-t4ikkevorgiblthtl93d0msp1b8st3hn.apps.googleusercontent.com',
    iosBundleId: 'com.example.travellookup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRLlxfgsz0VCQEVDclP0moUgSF1D5T8fE',
    appId: '1:650617212741:ios:1644ee49c2190c62f5382c',
    messagingSenderId: '650617212741',
    projectId: 'travellookup-3fda3',
    storageBucket: 'travellookup-3fda3.firebasestorage.app',
    iosClientId: '650617212741-t4ikkevorgiblthtl93d0msp1b8st3hn.apps.googleusercontent.com',
    iosBundleId: 'com.example.travellookup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCKnNutN-9l10UtlZQV7ow7cws9c8ezII',
    appId: '1:650617212741:web:126e0e177db024b3f5382c',
    messagingSenderId: '650617212741',
    projectId: 'travellookup-3fda3',
    authDomain: 'travellookup-3fda3.firebaseapp.com',
    storageBucket: 'travellookup-3fda3.firebasestorage.app',
    measurementId: 'G-HG1F4C5KRP',
  );
}
